export const heaterKit = [
        {
            id:'Heater-1',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Heater-1.mp3',
            audioID:'Q',
        },
        {
            id:'Heater-2',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Heater-2.mp3',
            audioID:'W',
        },
        {
            id:'Heater-3',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Heater-3.mp3',
            audioID:'E',
        },
        {
            id:'Heater-4',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Heater-4_1.mp3',
            audioID:'A',
        },
        {
            id:'Clap',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Heater-6.mp3',
            audioID:'S',
        },
        {
            id:'Open-HH',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Dsc_Oh.mp3',
            audioID:'D',
        },
        {
            id:"Kick-n'-Hat",
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Kick_n_Hat.mp3',
            audioID:'Z',
        },
        {
            id:'Kick',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/RP4_KICK_1.mp3',
            audioID:'X',
        },
        {
            id:'Closed-HH',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Cev_H2.mp3',
            audioID:'C',
        },
    ]