
export const smoothPianoKit = [
        {
            id:'Chord-1',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Chord_1.mp3',
            audioID:'Q',
        },
        {
            id:'Chord-2',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Chord_2.mp3',
            audioID:'W',
        },
        {
            id:'Chord-3',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Chord_3.mp3',
            audioID:'E',
        },
        {
            id:'Shaker',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Give_us_a_light.mp3',
            audioID:'A',
        },
        {
            id:'Open-HH',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Dry_Ohh.mp3',
            audioID:'S',
        },
        {
            id:'Closed-HH',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Bld_H1.mp3',
            audioID:'D',
        },
        {
            id:'Punchy-Kick',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/punchy_kick_1.mp3',
            audioID:'Z',
        },
        {
            id:'Side-Stick',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/side_stick_1.mp3',
            audioID:'X',
        },
        {
            id:'Snare',
            audioSrc:'https://s3.amazonaws.com/freecodecamp/drums/Brk_Snr.mp3',
            audioID:'C',
        },
    ]